### ISSUE TITLE
Fix outbound wireguard connections

### ISSUE THREAD

**Issue by jamesob** [chaincodelabs/bmon#6]
We use wireguard configurations with (essentially) `AllowedIPs = 0.0.0.0/0` (minus the bmon subnet) in order to simulate having geographically dispersed nodes; e.g. 
```yaml
  bitcoin-01: 
    tags: [bitcoind]
    check_host_keys: accept
    outbound_wireguard: wg-switzerland-01   <-- like this
    ...
    bitcoin_version: v23.0
```

However, for whatever reason when activating the wireguard connection (in addition to the `wg-bmon` connection), the node is unable to reach the internet. Investigate why this might be and fix it. 

Could be an issue with the VPN provider?
